
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 08 16:41:07 CET 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 4;
  public static final int IDENT = 10;
  public static final int PARO = 8;
  public static final int TRUE = 2;
  public static final int EQ = 12;
  public static final int EOF = 0;
  public static final int NL = 11;
  public static final int FALSE = 3;
  public static final int PARF = 9;
  public static final int error = 1;
  public static final int PRINT = 7;
  public static final int NOT = 6;
  public static final int OR = 5;
}

