
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Wed Oct 04 13:33:32 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DPT = 2;
  public static final int IDEN = 6;
  public static final int NBR = 8;
  public static final int PV = 7;
  public static final int TOTAL = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FAC = 4;
  public static final int FACTURE = 3;
}

