
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Wed Oct 18 13:56:13 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int moins = 4;
  public static final int divise = 6;
  public static final int paro = 7;
  public static final int EOF = 0;
  public static final int nb = 2;
  public static final int plus = 3;
  public static final int error = 1;
  public static final int parf = 8;
  public static final int fois = 5;
}

